### ISSUE TITLE
pull requests should have maximum size - discuss

### ISSUE THREAD

**Issue by taharrison** [burrowsyr/Styleguide#13]
richo is annoyed with people stressing out over having 100+ file code reviews.
can we find a way to keep this small ?

**Comment by westonized** [comment]
Well TFS interface has limit of 100:

![image](https://cloud.githubusercontent.com/assets/6041352/9329276/2266d7de-45a8-11e5-8c8e-d761577b1ac2.png)

So, that's the upper!

**Comment by gopher504** [comment]
Can certain file types be excluded, i.e. csproj? 

I recently reviewed a change where the number of housekeeping files exceeded the number of c#/html files that actually did business tasks.

**Comment by westonized** [comment]
AFAIK you can't exclude files from pull requests. And you don't want to exclude files like `csproj` from source control. Changes in `html` are just as important as any other change.

**Comment by gopher504** [comment]
I didn't mean to exclude csproj from source control, sorry I should have phrased it better. I was wondering if the file could be excluded from the list of files to review, unless there is some reason to review csproj and similar.

**Comment by westonized** [comment]
Yeah I don't think so :disappointed:
