### ISSUE TITLE
max columns in a line

### ISSUE THREAD

**Issue by taharrison** [burrowsyr/Styleguide#14]
80 ? 120?  enforce how?

discuss.

**Comment by westonized** [comment]
It's is already enforced to 120 by resharper settings. I think this is the default, but it is also set in our global base config file.

**Comment by westonized** [comment]
You just need to run code clean up explicitly, or configure silent clean up.

**Comment by taharrison** [comment]
So - is it worth max width being mentioned directly in style guide - or do we set it in resharper shared files, and then reference resharper settings as part of styleguide?

**Comment by westonized** [comment]
It is in there already "The width of a line should not exceed 120 characters to make sure you don’t have to scroll right."

**Comment by westonized** [comment]
Closing - already done
