### ISSUE TITLE
Should SOLID, TDD and Layering be mentioned?

### ISSUE THREAD

**Issue by Chess808** [burrowsyr/Styleguide#17]
No Mention of SOLID, TDD or Layer?

**Comment by westonized** [comment]
That is odd! I think SOLID and TDD yes.

But as for layering, if you mean prescribing a traditional layered architecture, then I'd say not include as that's an architectural decision of which there are more choices, such as onion, that might suit a project better.

[Uncle Bob - The Clean Architecture](http://blog.8thlight.com/uncle-bob/2012/08/13/the-clean-architecture.html)

**Comment by stevemchugh** [comment]
I agree, TDD and SOLID yes. As for layering, it might be worth having information about various layering architectures on a page somewhere for reference, but as Alan says choosing an architecture for a project is more about what the project needs and dictating one is not the right approach
